### PR TITLE
Small expand / collapse caret for ERC-20 tokens

### LINKED ISSUE #112: Expand arrow for ERC-20s [Duplicate]
> One last small design thing. I would suggest a little visual cue about the expanding of the list of tokens. For discovetability

**Link:** [Conversation with User j0ur](https://app.intercom.com/a/apps/j0fl7v0m/respond/inbox/all/conversations/21352319077)

**Customer:** [User j0ur](https://app.intercom.com/a/apps/j0fl7v0m/users/5c9953ca14894db09f4d0505/all-conversations)
**Customer ID:** 5A001CE8-F223-43FE-896F-8A9E70EB9E1D
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/j0fl7v0m/respond/inbox/all/conversations/21352319077) when this issue is closed.

### PR DESCRIPTION
**Pull request by jamierumbelow**
This PR resolves #112, by adding a small expand / collapse caret to the ERC-20 token list:

Capture d'écran 2019-04-02 12 53 56

### CODE REVIEW

**Review by ricburton — DISMISSED** [review]
Screen Shot 2019-04-02 at 13 29 13


Why is the caret sitting over the border? I slightly expanded the cell

**Review by ricburton — CHANGES_REQUESTED** [review]
Can we expand the cell so the caret is within it

**Comment by jamierumbelow** [comment]
It was supposed to be sitting 'over' the cell, to imply that it's an action of the cell list rather than of a specific cell. Anyway, my shit designing.

I like the idea of adding a little text like you did

**Comment by jamierumbelow** [comment]
(If anybody would like to tutor me on UI design I'll be very grateful!)

**Comment by jamierumbelow** [comment]
This PR now properly (and prettily!) resolves #112, by adding a new table cell for wallets with low-value tokens:

Capture d'écran 2019-04-03 21 36 05


It also resolves #157, by displaying low-value tokens when they're all that's available:

Capture d'écran 2019-04-03 21 35 36

**Review by einsteinx2 — APPROVED** [review]
Went over this with @jamierumbelow, it's good to go, merging

**Pull request merged**
