### PR TITLE
Add Close Button to Wallet Info Modal #106

### LINKED ISSUE #106: ↘️ Add a close button to modals
> <div class="intercom-container"></div>

**Link:** [Conversation with User zfpz](https://app.intercom.com/a/apps/j0fl7v0m/respond/inbox/all/conversations/21364629998)

**Customer:** [User zfpz](https://app.intercom.com/a/apps/j0fl7v0m/users/5c9a72af0f40d57d791360e6/all-conversations)
**Customer ID:** EED87AEC-CF9E-4EE3-AA27-31AA24AC0713
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/j0fl7v0m/respond/inbox/all/conversations/21364629998) when this issue is closed.

### PR DESCRIPTION
**Pull request by borwahs**
- Create new imageset asset for close icon.
- Display Close Button on Wallet Info View.
- Set Wallet label trailing edge to close button for overflow.

Screen Shot 2019-03-28 at 1 56 30 AM

Closes #106.

### CODE REVIEW

**Comment by ricburton** [comment]
🤘🤘🤘

Richard

**Review by ricburton — APPROVED** [review]
Looks great! We should add this to CDP views too

**Comment by borwahs** [comment]
oops! I forgot to add it to that view. Didn’t setup one up locally when testing. I’ll open a new PR with it there too.

**Comment by ricburton** [comment]
Thanks!

**Pull request merged**
