### PR TITLE
Add Ability to Edit Wallet Name (#118)

### LINKED ISSUE #118: Edit wallet names
Add an option to the wallet popover screen above Share

### PR DESCRIPTION
**Pull request by borwahs**
- Create helper funcs to build buttons and separators.
- Add method to update Wallet Name in Core Data.
- Show Edit Wallet Button and Alert Controller.
- Push notification on wallet name change and react.
- Set sizing of Wallet Info specially for iPhone SE.

Closes #118

### CODE REVIEW

**Comment by borwahs** [comment]
Special case for iPhone SE:

Screen Shot 2019-04-01 at 6 18 04 PM

**Comment by borwahs** [comment]
Flow:

Kapture 2019-04-01 at 18 21 29

**Comment by borwahs** [comment]
@einsteinx2  // two things:

1. I cannot figure out why the labels on the bottom two buttons are inset slightly.
2. I used a closure so we didn't have to couple CoreData logic into the UIView.

**Comment by borwahs** [comment]
Also, @ricburton do you have an icon I can use for the Edit button?

**Comment by ricburton** [comment]
renameButtonIcon@2x

renameButtonIcon@3x


Here you go @borwahs!

**Comment by borwahs** [comment]
@ricburton /// could you provide a version without white background? Or, if it's in the Figma, I can pull it from there.


Screen Shot 2019-04-02 at 1 43 10 PM

**Comment by ricburton** [comment]
Sorry! Will Do shortly.

**Comment by ricburton** [comment]
renameButtonIcon@3x
renameButtonIcon@2x

**Comment by borwahs** [comment]
@einsteinx2 & @ricburton  // this is ready for your review. Added the transparent icon.

**Comment by ricburton** [comment]
Sweet will dive in first thing tomorrow.

**Comment by einsteinx2** [comment]
@borwahs not sure why it's off, but I fixed the alignment with this:

`shareButton.titleEdgeInsets = UIEdgeInsets(top: 0, left: 4, bottom: 0, right: 0)`

**Comment by einsteinx2** [comment]
You can use constraints on the button's image view but not the title view, have to use edge insets, but it gets the job done

**Review by einsteinx2 — APPROVED** [review]

**Pull request merged**
