### PR TITLE
Amberdata

### LINKED ISSUE #116: 📈 Try Amber Data
They seem to have much better data and there are a lot of issues with Everex’s API. I *want* to pay for this.

I think it would solve a lot of other issues.

### PR DESCRIPTION
**Pull request by jamierumbelow**
This PR resolves #116 and #177.

It adds an `AmberdataAPI` class, responsible from pulling wallet ETH balance and tokens from Amberdata. It makes some small changes to how wallets are displayed, and 

Some things that don't work so well:

* **It's still slow.** We need to make two calls per wallet in order to collect the relevant information from Amberdata. It's faster than Ethplorer, I think, but could be improved with some selective multithreading.
* **Occasionally the API will throw an error**, and if this happens on the first load, the app will break. We should think about how to handle these cases more elegantly.

### N.B.

The line:

    export AMBERDATA_API_KEY=""

Will need to be added to your **apikeys.sh** file.

### $BAL contract

This PR also checks against the $BAL contract address when notifying the app that the user carries $BAL. It won't remove other BALs from the wallet, but it won't allow the user to access features when she doesn't hodl the one true BAL.

### CODE REVIEW

**Comment by TrevorJTClarke** [comment]
Hey @jamierumbelow this is looking good!
I work with Amberdata, happy to help on any questions you have.

Regarding above:
Some things that don't work so well:
It's still slow. We need to make two calls per wallet in order to collect the relevant information from Amberdata. It's faster than Ethplorer, I think, but could be improved with some selective multithreading.
- TC: We're still working on making it faster :) We also are playing around with different ways of delivering the data in a single call in a performant way. You are needing ETH balance + token balances in a single call correct? (And multi-address if possible?)

Occasionally the API will throw an error, and if this happens on the first load, the app will break. We should think about how to handle these cases more elegantly.
- TC: I'd love to know the error you're seeing

**Comment by jamierumbelow** [comment]
Hi @TrevorJTClarke, thanks for getting in touch.

* Yes - eth balance, token balance and prices all in one, ideally for more than one address, would be brilliant. I presume you're looking into GraphQL?
* Either connection errors client-side, or rate-limiting errors from my non-pro account. Nothing for you to worry about :)

**Comment by TrevorJTClarke** [comment]
@jamierumbelow sounds good:
* We've been playing with graphql, but have that further along in the roadmap. We should be able to send some endpoint updates next week that you can test. I'd love feedback on those to make sure we're meeting your needs.
* Okay 👍 , lemme know if you have any issues needing my help

**Review by einsteinx2 — APPROVED** [review]
Looks good!

**Pull request merged**
