### PR TITLE
Add Button Sizing and Haptic Feedback #59

### PR DESCRIPTION
**Pull request by borwahs**
- Prepare and call Haptic Feedback on Add Wallet action.
- Run Haptic Feedback on Eth Wallet Add success.
- Create new imageset Asset using Plus Icon.
- Change Add Wallet button to use image and title.

Issue #59

### CODE REVIEW

**Comment by borwahs** [comment]
Here is the Add Button I changed to:

IMG_6682

Let me know if you like that for a bigger touch target.

**Comment by borwahs** [comment]
One thing I just thought of is that if support for pre iPhone 7 devices is needed, we will need to use the original taptic engine. Let me know your thoughts on going that route.

**Comment by einsteinx2** [comment]
For now I think it's fine if this only works on iPhone 7 and up, as long as it doesn't crash or cause other problems on older devices.

**Comment by borwahs** [comment]
Playing with my change to the Add Button, I think I should remove the text. It looks a bit too bland. Maybe the grey is the issue?

**Review by ricburton — APPROVED** [review]
I think adding text is a good call. Will see how this looks.

Thanks for the ... addition!

**Pull request merged**
